homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: 'America/New_York'
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

lovelace:
  mode: yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sensor.dark_sky_daytime_high_temperature_0
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0
      - sensor.dark_sky_overnight_low_temperature_0
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_0
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_0
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0
      - sensor.dark_sky_temperature
      - sensor.dark_sky_temperature_0      

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: darksky
    api_key: !secret darksky
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature
      - temperature_high
      - temperature_low
      - precip_probability
      - precip_type
      - precip_intensity
    units: 'us'
    update_interval: '00:10'
  - platform: mta_subway
    line:
      - 1
      - 2
      - 3
      - A
      - C

weather:
  - platform: darksky
    api_key: !secret darksky
    units: 'us'

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

python_script:

hue:
  bridges:
    - host: 192.168.1.186
      allow_unreachable: true
      allow_hue_groups: true

ifttt:
  key: !secret kmc_api

device_tracker:
  - platform: quantum_gateway
    host: 192.168.1.1
    password: !secret gateway_pass

http:
  api_password: !secret api_password
  ssl_certificate: /etc/letsencrypt/live/gabeandsarah.hopto.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/gabeandsarah.hopto.org/privkey.pem
  trusted_networks:
    - '127.0.0.1'
    - '::1'
    - '192.168.1.0/24'
    - 'fd00::/8'

alexa:

intent_script:
  RunScriptIntent:
    speech:
      text: Did it
    action:
      service: notify.notify
      data_template:
        message: Hello

notify:
  platform: ios

ios:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
